controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use yii\data\ActiveDataProvider;
use app\models\Emple;
use \app\models\Depart;
use yii\data\SqlDataProvider;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    
    // formato por defecto del grid
    public $formatoGrid = "{summary}<br /><br />{items}{pager}";
    
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }
    
    public function actionConsulta1() {
        $query = Emple::find()->select("emple.*");
        
        $dataProvider = new ActiveDataProvider([
                'query' => $query,
                'pagination' => [
                  'pageSize' => 2,
                ],
        ]);
        
        return $this->render('_index', [
            'titulo' => 'Consulta 1',
            'descripcion' => 'SELECT * FROM emple',
            'dataProvider' => $dataProvider,
            'columnas' => ['emp_no', 'apellido', 'oficio', 'dir', 'fecha_alt', 'salario', 'comision', 'dept_no'],
        ]);
    }

    public function actionConsulta2() {
        $query = Depart::find()->select("depart.*");
        
        $dataProvider = new ActiveDataProvider([
                'query' => $query,
                'pagination' => [
                  'pageSize' => 2,
                ],
        ]);
        
        return $this->render('_index', [
            'titulo' => 'Consulta 2',
            'descripcion' => 'SELECT * FROM depart',
            'dataProvider' => $dataProvider,
            'columnas' => ['dept_no', 'dnombre', 'loc'],
        ]);
    }
    
    public function actionConsulta3() {
        $query = Emple::find()->select("apellido, oficio");
        
        $dataProvider = new ActiveDataProvider([
                'query' => $query,
                'pagination' => [
                  'pageSize' => 2,
                ],
        ]);
        
        return $this->render('_index', [
            'titulo' => 'Consulta 3',
            'descripcion' => 'SELECT apellido, oficio FROM emple',
            'dataProvider' => $dataProvider,
            'columnas' => ['apellido', 'oficio'],
        ]);
    }

    public function actionConsulta4() {
        $query = Depart::find()->select("loc, dept_no");
        
        $dataProvider = new ActiveDataProvider([
                'query' => $query,
                'pagination' => [
                  'pageSize' => 2,
                ],
        ]);
        
        return $this->render('_index', [
            'titulo' => 'Consulta 4',
            'descripcion' => 'SELECT loc, dept_no FROM depart',
            'dataProvider' => $dataProvider,
            'columnas' => ['loc', 'dept_no'],
        ]);
    }

    public function actionConsulta5() {
        $query = Depart::find()->select("dept_no, dnombre, loc");
        
        $dataProvider = new ActiveDataProvider([
                'query' => $query,
                'pagination' => [
                  'pageSize' => 2,
                ],
        ]);
        
        return $this->render('_index', [
            'titulo' => 'Consulta 5',
            'descripcion' => 'SELECT dept_no, dnombre, loc FROM depart',
            'dataProvider' => $dataProvider,
            'columnas' => ['dept_no', 'dnombre', 'loc'],
        ]);
    }
    
    public function actionConsulta6() {
        $provider = new SqlDataProvider([
            'sql' => 'SELECT COUNT(*) FROM emple',
        ]);
              
        return $this->render('_index', [
            'titulo' => 'Consulta 6',
            'descripcion' => 'SELECT COUNT(*) FROM emple',
            'dataProvider' => $provider,
            'columnas' => [],
        ]);
    }
    
    public function actionConsulta6a() {
        $provider = new ActiveDataProvider([
            'query' => Emple::find()->select("count(*) as total"),
            'totalCount'=>1,                
        ]);
        
        // Quita el texto que nos dice los registros activos y el número de registros.
        $this->formatoGrid = "{items}";
              
        return $this->render('_index', [
            'titulo' => 'Consulta 6a',
            'descripcion' => 'SELECT COUNT(*) FROM emple',
            'dataProvider' => $provider,
            'columnas' => ['total'],
            
        ]);
    }

    public function actionConsulta7() {
        $query = Emple::find()->select("emple.*")->orderBy(["apellido" => SORT_ASC]);
        
        $dataProvider = new ActiveDataProvider([
                'query' => $query,
                'pagination' => [
                  'pageSize' => 2,
                ],
        ]);
        
        return $this->render('_index', [
            'titulo' => 'Consulta 7',
            'descripcion' => 'SELECT * FROM emple ORDER BY apellido ASC',
            'dataProvider' => $dataProvider,
            'columnas' => ['emp_no', 'apellido', 'oficio', 'dir', 'fecha_alt', 'salario', 'comision', 'dept_no'],
        ]);
    }

    public function actionConsulta8() {
        $query = Emple::find()->select("emple.*")->orderBy(["apellido" => SORT_DESC]);
        
        $dataProvider = new ActiveDataProvider([
                'query' => $query,
                'pagination' => [
                  'pageSize' => 2,
                ],
        ]);
        
        return $this->render('_index', [
            'titulo' => 'Consulta 8',
            'descripcion' => 'SELECT * FROM emple ORDER BY apellido DESC',
            'dataProvider' => $dataProvider,
            'columnas' => ['emp_no', 'apellido', 'oficio', 'dir', 'fecha_alt', 'salario', 'comision', 'dept_no'],
        ]);
    }

    public function actionConsulta9() {
        $dataProvider = new SqlDataProvider([
                'sql' => 'SELECT COUNT(*) FROM depart',
        ]);
        
        return $this->render('_index', [
            'titulo' => 'Consulta 9',
            'descripcion' => 'SELECT COUNT(*) FROM depart',
            'dataProvider' => $dataProvider,
            'columnas' => [],
        ]);
    }
    
    public function actionConsulta10() {
        $count = Yii::$app->db
                ->createCommand('SELECT COUNT(*) FROM emple')
                ->queryScalar();

        $dataProvider = new SqlDataProvider([
                'sql' => 'SELECT * FROM emple ORDER BY dept_no DESC',
                'totalCount' => $count,
                'pagination' => [
                    'pageSize' => 2,
                ],
        ]);
        
        return $this->render('_index', [
            'titulo' => 'Consulta 10',
            'descripcion' => 'SELECT * FROM depart ORDER BY dept_no DESC',
            'dataProvider' => $dataProvider,
            'columnas' => ['emp_no', 'apellido', 'oficio', 'dir', 'fecha_alt', 'salario', 'comision', 'dept_no'],
        ]);
    }

    public function actionConsulta11() {
        $count = Yii::$app->db
                ->createCommand('SELECT COUNT(*) FROM emple')
                ->queryScalar();

        $dataProvider = new SqlDataProvider([
                'sql' => 'SELECT * FROM emple ORDER BY dept_no DESC, oficio ASC',
                'totalCount' => $count,
                'pagination' => [
                    'pageSize' => 2,
                ],
        ]);
        
        return $this->render('_index', [
            'titulo' => 'Consulta 11',
            'descripcion' => 'SELECT * FROM emple ORDER BY dept_no DESC, oficio ASC',
            'dataProvider' => $dataProvider,
            'columnas' => ['emp_no', 'apellido', 'oficio', 'dir', 'fecha_alt', 'salario', 'comision', 'dept_no'],
        ]);
    }

    public function actionConsulta12() {
        $count = Yii::$app->db
                ->createCommand('SELECT COUNT(*) FROM emple')
                ->queryScalar();

        $dataProvider = new SqlDataProvider([
                'sql' => 'SELECT * FROM emple ORDER BY dept_no DESC, apellido ASC',
                'totalCount' => $count,
                'pagination' => [
                    'pageSize' => 2,
                ],
        ]);
        
        return $this->render('_index', [
            'titulo' => 'Consulta 12',
            'descripcion' => 'SELECT * FROM emple ORDER BY dept_no DESC, apellido ASC',
            'dataProvider' => $dataProvider,
            'columnas' => ['emp_no', 'apellido', 'oficio', 'dir', 'fecha_alt', 'salario', 'comision', 'dept_no'],
        ]);
    }

    public function actionConsulta13() {
        $query = Emple::find()->select("emp_no")->where([">","salario","2000"]);

        $dataProvider = new ActiveDataProvider([
                'query' => $query,
                'pagination' => [
                    'pageSize' => 2,
                ],
        ]);
        
        return $this->render('_index', [
            'titulo' => 'Consulta 13',
            'descripcion' => 'SELECT emp_no FROM emple WHERE salario > 2000',
            'dataProvider' => $dataProvider,
            'columnas' => ['emp_no'],
        ]);
    }

    public function actionConsulta14() {
        $query = Emple::find()->select(["emp_no", "apellido"])->where(["<","salario","2000"]);

        $dataProvider = new ActiveDataProvider([
                'query' => $query,
                'pagination' => [
                    'pageSize' => 2,
                ],
        ]);
        
        return $this->render('_index', [
            'titulo' => 'Consulta 14',
            'descripcion' => 'SELECT emp_no, apellido FROM emple WHERE salario < 2000',
            'dataProvider' => $dataProvider,

views/site/_index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Noticias';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="noticias-index">
    <div class="jumbotron">
    <h1><?= Html::encode($titulo) ?></h1>

    <p>
        <?= $descripcion ?>
    </p>
    </div>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => $columnas,
        'layout' => Yii::$app->controller->formatoGrid
    ]); ?>


</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php
use yii\helpers\Html;

/* @var $this yii\web\View */

?>
<div class="container-fluid">
    <div class="row">
      <div class="col-lg-2 col-md-12">
        <div class="thumbnail">
          <div class="caption">
            <h3>Consulta 1</h3>
            <p>Lista todos los Empleados</p>
            <p><?= Html::a('Consulta 1', ['/site/consulta1'], ['class'=>'btn btn-primary grid-button']) ?></p>
          </div>
        </div>
      </div>
      <div class="col-lg-2 col-md-12">
        <div class="thumbnail">
          <div class="caption">
            <h3>Consulta 2</h3>
            <p>Lista todos los Departamentos</p>
            <p><?= Html::a('Consulta 2', ['/site/consulta2'], ['class'=>'btn btn-primary grid-button']) ?></p>
          </div>
        </div>
      </div>
      <div class="col-lg-2 col-md-12">
        <div class="thumbnail">
          <div class="caption">
            <h3>Consulta 3</h3>
            <p>Mostrar el apellido y el oficio de cada empleado</p>
            <p><?= Html::a('Consulta 3', ['/site/consulta3'], ['class'=>'btn btn-primary grid-button']) ?></p>
          </div>
        </div>
      </div>
      <div class="col-lg-2 col-md-12">
        <div class="thumbnail">
          <div class="caption">
            <h3>Consulta 4</h3>
            <p>Mostrar localización y número de cada Departamento</p>
            <p><?= Html::a('Consulta 4', ['/site/consulta4'], ['class'=>'btn btn-primary grid-button']) ?></p>
          </div>
        </div>
      </div>
      <div class="col-lg-2 col-md-12">
        <div class="thumbnail">
          <div class="caption">
            <h3>Consulta 5</h3>
            <p>Mostrar número, nombre y localización de cada Departamento</p>
            <p><?= Html::a('Consulta 5', ['/site/consulta5'], ['class'=>'btn btn-primary grid-button']) ?></p>
          </div>
        </div>
      </div>
      <div class="col-lg-2 col-md-12">
        <div class="thumbnail">
          <div class="caption">
            <h3>Consulta 6</h3>
            <p>Indicar el número  de empleados que hay</p>
            <p><?= Html::a('Consulta 6', ['/site/consulta6'], ['class'=>'btn btn-primary grid-button']) ?></p>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-2 col-md-12">
        <div class="thumbnail">
          <div class="caption">
            <h3>Consulta 7</h3>
            <p>Mostar Datos de los empleados ordenados por apellidos de forma ascendente</p>
            <p><?= Html::a('Consulta 7', ['/site/consulta7'], ['class'=>'btn btn-primary grid-button']) ?></p>
          </div>
        </div>
      </div>
      <div class="col-lg-2 col-md-12">
        <div class="thumbnail">
          <div class="caption">
            <h3>Consulta 8</h3>
            <p>Mostar Datos de los empleados ordenados por apellidos de forma descendente</p>
            <p><?= Html::a('Consulta 8', ['/site/consulta8'], ['class'=>'btn btn-primary grid-button']) ?></p>
          </div>
        </div>
      </div>
      <div class="col-lg-2 col-md-12">
        <div class="thumbnail">
          <div class="caption">
            <h3>Consulta 9</h3>
            <p>Indicar el número  de departamentos que hay</p>
            <p><?= Html::a('Consulta 9', ['/site/consulta9'], ['class'=>'btn btn-primary grid-button']) ?></p>
          </div>
        </div>
      </div>
      <div class="col-lg-2 col-md-12">
        <div class="thumbnail">
          <div class="caption">
            <h3>Consulta 10</h3>
            <p>Datos de los empleados ordenados por número de departamento descendentemente</p>
            <p><?= Html::a('Consulta 10', ['/site/consulta10'], ['class'=>'btn btn-primary grid-button']) ?></p>
          </div>
        </div>
      </div>
      <div class="col-lg-2 col-md-12">
        <div class="thumbnail">
          <div class="caption">
            <h3>Consulta 11</h3>
            <p>Datos de los empleados ordenados por número de departamento descendentemente y por oficio ascendente</p>
            <p><?= Html::a('Consulta 11', ['/site/consulta11'], ['class'=>'btn btn-primary grid-button']) ?></p>
          </div>
        </div>
      </div>
      <div class="col-lg-2 col-md-12">
        <div class="thumbnail">
          <div class="caption">
            <h3>Consulta 12</h3>
            <p>Datos de los empleados ordenados por número de departamento descendentemente y por apellido ascendentemente</p>
            <p><?= Html::a('Consulta 12', ['/site/consulta12'], ['class'=>'btn btn-primary grid-button']) ?></p>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-2 col-md-12">
        <div class="thumbnail">
          <div class="caption">
            <h3>Consulta 13</h3>
            <p>Mostrar los códigos de los empleados cuyo salario sea mayor que 2000</p>
            <p><?= Html::a('Consulta 13', ['/site/consulta13'], ['class'=>'btn btn-primary grid-button']) ?></p>
          </div>
        </div>
      </div>
      <div class="col-lg-2 col-md-12">
        <div class="thumbnail">
          <div class="caption">
            <h3>Consulta 14</h3>
            <p>Mostrar los códigos y apellidos de los empleados cuyo salario sea menor que 2000</p>
            <p><?= Html::a('Consulta 14', ['/site/consulta14'], ['class'=>'btn btn-primary grid-button']) ?></p>
          </div>
        </div>
      </div>
      <div class="col-lg-2 col-md-12">
        <div class="thumbnail">
          <div class="caption">
            <h3>Consulta 15</h3>
            <p>Mostrar los datos de los empleados cuyo salario este entre 1500 y 2500</p>
            <p><?= Html::a('Consulta 15', ['/site/consulta15'], ['class'=>'btn btn-primary grid-button']) ?></p>
          </div>
        </div>
      </div>
      <div class="col-lg-2 col-md-12">
        <div class="thumbnail">
          <div class="caption">
            <h3>Consulta 16</h3>
            <p>Mostrar los datos de los empleados cuyo oficio sea 'ANALISTA'</p>
            <p><?= Html::a('Consulta 16', ['/site/consulta16'], ['class'=>'btn btn-primary grid-button']) ?></p>
          </div>
        </div>
      </div>
      <div class="col-lg-2 col-md-12">
        <div class="thumbnail">
          <div class="caption">
            <h3>Consulta 17</h3>
            <p>Mostrar los datos de los empleados cuyo oficio sea ANALISTA y ganen mas de 2000 €</p>
            <p><?= Html::a('Consulta 17', ['/site/consulta17'], ['class'=>'btn btn-primary grid-button']) ?></p>
          </div>
        </div>
      </div>
      <div class="col-lg-2 col-md-12">
        <div class="thumbnail">
          <div class="caption">
            <h3>Consulta 22</h3>
            <p>Mostrar los apellidos del empleado que mas gana</p>
            <p><?= Html::a('Consulta 22', ['/site/consulta22'], ['class'=>'btn btn-primary grid-button']) ?></p>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-2 col-md-12">
        <div class="thumbnail">
          <div class="caption">
            <h3>Consulta 24</h3>
            <p>Mostrar un listado de los distintos meses en que los empleados se han dado de alta</p>
            <p><?= Html::a('Consulta 24', ['/site/consulta24'], ['class'=>'btn btn-primary grid-button']) ?></p>
          </div>
        </div>
      </div>
      <div class="col-lg-2 col-md-12">
        <div class="thumbnail">
          <div class="caption">
            <h3>Consulta 28</h3>
            <p>Realizar un listado donde nos coloque el apellido del empleado y el nombre del departamento al que pertenece</p>
            <p><?= Html::a('Consulta 28', ['/site/consulta28'], ['class'=>'btn btn-primary grid-button']) ?></p>
          </div>
        </div>
      </div>
      <div class="col-lg-2 col-md-12">
        <div class="thumbnail">
          <div class="caption">
            <h3>Consulta 30</h3>
            <p>Listar el número de empleados por departamento</p>
            <p><?= Html::a('Consulta 30', ['/site/consulta30'], ['class'=>'btn btn-primary grid-button']) ?></p>
          </div>
        </div>
      </div>
      <div class="col-lg-2 col-md-12">
        <div class="thumbnail">
          <div class="caption">
            <h3>Consulta 31</h3>
            <p>Listar el número de empleados por departamento que salga el nombre del departamento</p>
            <p><?= Html::a('Consulta 31', ['/site/consulta31'], ['class'=>'btn btn-primary grid-button']) ?></p>
          </div>
        </div>
      </div>
      <div class="col-lg-2 col-md-12">
        <div class="thumbnail">
          <div class="caption">
            <h3>Consulta 33</h3>
            <p>Seleccionar de la tabla EMPLE los empleados cuyo apellido empiece por 'A'. Listar el apellido de los empleados</p>
            <p><?= Html::a('Consulta 33', ['/site/consulta33'], ['class'=>'btn btn-primary grid-button']) ?></p>
          </div>
        </div>
      </div>
    </div>
</div>